# SPDX-FileCopyrightText: d-k-bo <d-k-bo@mailbox.org>
# SPDX-License-Identifier: CC0-1.0

[package]
name = "televido"
version = "0.5.1"
edition = "2024"
publish = false

[dependencies]
adw = { package = "libadwaita", version = "0.8.1", features = ["v1_8"] }
clapper-player = { version = "0.10" }
clapper-player-gtk = { version = "0.10" }
eyre = "0.6.12"
gettext-rs = { version = "0.7.7", features = ["gettext-system"] }
gsettings-macro = "0.2.2"
gst = { version = "0.24.4", package = "gstreamer", features = ["v1_26"] }
gtk = { version = "0.10.3", package = "gtk4", features = ["gnome_49", "blueprint"] }
gvdb-macros = "0.1.15"
html2pango = "0.6.0"
indexmap = { version = "2.13.0", features = ["serde"] }
mediathekviewweb = { version = "0.5.0" }
phf = { version = "0.13.1", features = ["macros"] }
reqwest = { version = "0.13.2", default-features = false, features = ["json", "native-tls"] }
serde = { version = "1.0.228", features = ["derive"] }
smart-default = "0.7.1"
time = { version = "0.3.47", features = ["parsing", "serde"] }
tokio = { version = "1.49.0", features = ["fs", "time", "rt-multi-thread", "macros"] }
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.22", features = ["env-filter"] }
zbus = { version = "5.13.2", default-features = false, features = ["tokio"] }

[profile.dev.build-override]
opt-level = 3
